### ISSUE TITLE
Issues not displaying author and category

### ISSUE THREAD

**Issue by zeshhaan** [jaydanurwin/astro-sanity-minimal-starter#8]
The groq query for allPosts doesn't fetch current category title and slug. Also it doesn't fetch author name.

Here is how it looks now
```gql
export const allPosts = `*[_type == 'post']{categories[]->{slug, title}, ...} | order(publishedAt desc)`;
```

Here is the fix that worked for me
```gql
export const allPosts = `*[_type == 'post']{..., categories[]->{title, slug}, author -> {name}} | order(publishedAt desc)`;
```

Thanks

**Comment by jaydanurwin** [comment]
Thanks for filing this issue @zeshhaan! It should be fixed in the `next` branch already and will be merged in with #12 after Astro releases their official v1.0 version which (hopefully) is very soon.
